spring:
  application.name: first-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}


management:
  endpoints.web.exposure.include: "*"

test:
  env: dev
  servers:
    - server1.example.com
    - server2.example.com
    - server3.example.com
  credentials:
    username: admin
    password: secret
    roles:
      dev: developer
      qa: tester
      prod: admin
