spring:
  application.name: third-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    busrefresh:
      access: unrestricted
