test:
  env: dev
  servers:
    - server1.example.com
    - server2.example.com
    - server3.example.com
  credentials:
    username: user
    password: secret
    roles:
      dev: developer
      qa: tester
      prod: admin

server.port: 8081